Algoritmo "ex_007"

Var
   numero, dobro, terca_parte : real

Inicio
   //Entrada de dados
   escreva("Digite um número: ")
   leia(numero)

   dobro <- numero * 2 //Fórmula para calcular a multiplicação
   terca_parte <- numero / 3 //Fórmula para calcular a terça parte

   //Saída de dados
   escreva("O dobro do número digitado é ", dobro, " e a terça parte é ", terca_parte)

Fimalgoritmo